services:
 apache:
  image: httpd:latest
  volumes:
   - ./codi/starship-sorades-13k:/usr/local/apache2/htdocs
  expose: 
   - "80"

 nginx:
  image: nginx:latest
  container_name: cNginx
  ports:
   - "80:8000"
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf
  depends_on:
   - apache
