version: '3.8'

services:
 sMysql:
  image: mysql:9.1
  container_name: cmysql
  ports:
   - "33306:3306"
  environment:
   MYSQL_DATABASE: "bdPj9f4a87apl2" 
   MYSQL_USER: "asix2"
   MYSQL_PASSWORD: "Fjeclot2425@"
   MYSQL_ROOT_PASSWORD: "Fjeclot2425@"   
  volumes:
   - ./sql:/sql
   - vDades:/var/lib/mysql
  networks:
   - xPj9f4a87apl2
 swebapp:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: cWebApp
  ports:
   - "8080:80"
  volumes:
   - ./app:/var/www/html
  depends_on:
   - sMysql
  networks:
   - xPj9f4a87apl2
networks:
  xPj9f4a87apl2:
   driver: bridge
volumes:
  sql:
   driver: local
  vDades:
   driver: local
